# Generated by Django 4.2.29 on 2026-04-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubmittednews',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='usersubmittednews',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='usersubmittednews',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='usersubmittednews',
            name='status',
        ),
        migrations.AddField(
            model_name='usersubmittednews',
            name='embedding_vector',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubmittednews',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
    ]
